# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-29 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20171227_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='imgae',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='imgae',
            new_name='image',
        ),
    ]
