# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-02 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_image_tags'),
        ('notifications', '0003_auto_20180102_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Comment'),
        ),
    ]
