# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-02 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20180102_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['created_at']},
        ),
    ]
